name: Trevor
favicon: null
layout_spectrum: 0.8870181422680616
typography_spectrum: 0.9607077855616808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5452899308875203
  lightness: 0.8084942465648055
  saturation: 0.1695115235634148
  rhythmicContrast: 0.4857124639675021
purpose: []
